### PR TITLE
Fix - Removal of unused fields on Pool and Gate Entities and addition of Delivery Service Qualifier

### LINKED ISSUE #281: Persistence: Remove Admin Level 2 - 4 from alternative address
Overtake the API changes for issue  #176 to the persistence layer of Pool and Gate.

### LINKED ISSUE #282: Persistence: Remove Street from Alternative Address
Overtake the API changes from issue  #178  to the persistence layer of Gate and Pool.

### LINKED ISSUE #283: Persistence: Remove Districts in Alternative Address
Overtake the API changes from issue #182 to the persistence layer of Gate and Pool.

### LINKED ISSUE #284: Persistence: Delivery Service Qualifier in Alternative Postal Address
Overtake the API changes from issue #202  to the persistence layer of Gate and Pool

### PR DESCRIPTION
**Pull request by alexsilva-CGI**
---
name: Removal of unused fields on Pool and Gate Entities and addition of Delivery Service Qualifier
---

## Description

This PR removes unused and unnecessary columns in the Entities and Database from the Gate and Pool, and addition of  Delivery Service Qualifier on the Alternative Postal Address of both Pool and Gate.

Related issues: fix #284 fix #281 fix #282 fix #283

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [x] DEPENDENCIES are up to date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [x] Copyright and license header are present on all affected files

### CODE REVIEW

File: bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/entity/AlternativePostalAddress.kt [hunk 1]
```diff
@@ -105,4 +66,7 @@ class AlternativePostalAddress(
      */
     @Column(name = "alt_delivery_service_number")
     val deliveryServiceNumber: String = "",
+
+    @Column(name = "alt_delivery_service_qualifier")
+    val deliveryServiceQualifier: String = "",
```
Comment (nicoprow) [inline bpdm-pool/src/main/kotlin/org/eclipse/tractusx/bpdm/pool/entity/AlternativePostalAddress.kt:71]: Since this is a new column added here, the existing business partners have NULL written in it. Since this entity expects a non null value it leads to an error. In general, if an entity field is not nullable, its column should be not nullable

File: bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/entity/AlternativePostalAddress.kt [hunk 2]
```diff
@@ -98,4 +65,7 @@ class AlternativePostalAddress(
      */
     @Column(name = "alt_delivery_service_number")
     val deliveryServiceNumber: String = "",
+
+    @Column(name = "alt_delivery_service_qualifier")
+    val deliveryServiceQualifier: String = "",
```
Comment (nicoprow) [inline bpdm-gate/src/main/kotlin/org/eclipse/tractusx/bpdm/gate/entity/AlternativePostalAddress.kt:70]: Since this is a new column added here, the existing business partners have NULL written in it. Since this entity expects a non null value it leads to an error. In general, if an entity field is not nullable, its column should be not nullable

**Review by nicoprow — CHANGES_REQUESTED** [review]
Some issues while testing

**Review by nicoprow — APPROVED** [review]
